"""Graph-aware second-layer scoring and abuse-ring detection."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha1
from time import perf_counter
from typing import Any, Optional

from sqlalchemy.orm import Session

from database.models import GraphEdge, Transaction


@dataclass
class L2Score:
    """Graph-risk assessment for a transaction escalated from L1."""

    score: float
    ring_detected: bool
    ring_id: Optional[str]
    ring_score: float
    attention_weights: list[dict[str, Any]]
    latency_ms: float


class GraphRiskEngine:
    """Detect shared-entity abuse patterns from the persisted Phase 1 graph.

    The graph signals are useful before a trained HeteroGNN checkpoint is
    available and remain directly explainable in the dashboard. They mirror the
    node relations consumed by the GNN training path: device, IP, card, and
    VPA reuse across otherwise distinct customer identities.
    """

    def __init__(self, db: Session):
        self.db = db

    def score(self, transaction: Transaction) -> L2Score:
        started = perf_counter()
        entities = self._entities(transaction)
        attention: list[dict[str, Any]] = []
        score = 0.0
        implicated_users: set[str] = set()

        for entity_type, entity_id, threshold, weight in entities:
            user_count, users = self._shared_user_count(entity_type, entity_id)
            implicated_users.update(users)
            strength = min(user_count / threshold, 1.0)
            contribution = strength * weight if user_count >= 2 else 0.0
            score += contribution
            attention.append({
                "entity_type": entity_type,
                "entity_id": entity_id,
                "connected_users": user_count,
                "weight": round(contribution, 3),
            })

        # Persisted graph data is generated by Phase 1. For brand-new input
        # before the next graph write, transaction history offers the same
        # shared-device and shared-IP coverage.
        if not implicated_users:
            attention = self._history_attention(transaction)
            score = sum(item["weight"] for item in attention)

        ring_score = min(1.0, score)
        ring_detected = ring_score >= 0.45 and len(implicated_users) >= 2
        ring_id = None
        if ring_detected:
            fingerprint = "|".join(sorted(implicated_users | {transaction.customer_id}))
            ring_id = f"ring_{sha1(fingerprint.encode()).hexdigest()[:12]}"

        return L2Score(
            score=round(ring_score, 4),
            ring_detected=ring_detected,
            ring_id=ring_id,
            ring_score=round(ring_score, 4),
            attention_weights=attention,
            latency_ms=round((perf_counter() - started) * 1_000, 3),
        )

    @staticmethod
    def _entities(transaction: Transaction) -> list[tuple[str, str, int, float]]:
        entities: list[tuple[str, str, int, float]] = []
        if transaction.device_id:
            entities.append(("device", transaction.device_id, 5, 0.65))
        if transaction.ip_address:
            parts = transaction.ip_address.split(".")
            subnet = ".".join(parts[:3]) + ".0/24" if len(parts) == 4 else transaction.ip_address
            entities.append(("ip", subnet, 10, 0.30))
        if transaction.payment_method in ["credit_card", "debit_card"] and transaction.card_last4:
            card = f"{transaction.card_network}_{transaction.card_issuer}_{transaction.card_last4}"
            entities.append(("card", card, 3, 0.50))
        if transaction.payment_method == "upi" and transaction.vpa:
            entities.append(("vpa", transaction.vpa, 4, 0.50))
        return entities

    def _shared_user_count(self, entity_type: str, entity_id: str) -> tuple[int, set[str]]:
        users = {
            value[0]
            for value in (
                self.db.query(GraphEdge.source_id)
                .filter(
                    GraphEdge.source_type == "user",
                    GraphEdge.target_type == entity_type,
                    GraphEdge.target_id == entity_id,
                )
                .distinct()
                .all()
            )
        }
        return len(users), users

    def _history_attention(self, transaction: Transaction) -> list[dict[str, Any]]:
        results: list[dict[str, Any]] = []
        if transaction.device_id:
            users = (
                self.db.query(Transaction.customer_id)
                .filter(Transaction.device_id == transaction.device_id)
                .distinct()
                .count()
            )
            if users >= 2:
                results.append({"entity_type": "device", "connected_users": users, "weight": min(users / 5, 1.0) * 0.65})
        if transaction.ip_address:
            users = (
                self.db.query(Transaction.customer_id)
                .filter(Transaction.ip_address == transaction.ip_address)
                .distinct()
                .count()
            )
            if users >= 2:
                results.append({"entity_type": "ip", "connected_users": users, "weight": min(users / 10, 1.0) * 0.30})
        return results
